---

#- name: Debug
#  debug:
#    msg: "{{ domains.0 }}"


- name: Check if Apache exists
  stat: path=/etc/init.d/apache2
  register: service_status


- name: Stop Apache service
  service: name=apache2 state=stopped
  when: service_status.stat.exists
  register: service_stopped


- name: Remove Apache
  become: true
  package:
    name: "{{ item }}"
    state: absent

  with_items:
    - apache
    - apache2


- name: NGINX | Install system packages
  become: true
  package:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present

  with_items:
    - nginx


- name: NGINX | Create Nginx configuration file
  become: true
  template:
    src: nginx.conf.j2
    dest: "{{ host.home }}conf/nginx.conf"
  when: tls is not defined
  notify:
    - restart nginx


- name: NGINX | Create Nginx TLS configuration file
  become: true
  template:
    src: nginx_tls.conf.j2
    dest: "{{ host.home }}conf/nginx.conf"
  when: tls is defined
  notify:
    - restart nginx


- name: NGINX | Create Nginx symlink
  become: true
  file:
    path: /etc/nginx/sites-enabled/{{ project.name }}.conf
    src: "{{ host.home }}conf/nginx.conf"
    force: true
    state: link

  notify:
    - restart nginx

