---

- name: Install system packages
  package:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present

  with_items:
    - nginx


#- name: Generate Diffie-Hellman params
#  become: true
#  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048


- name: Create Nginx configuration file
  template:
    src: nginx.j2
    dest: "{{ host.home }}conf/nginx.conf"
    #dest: /etc/nginx/sites-enabled/{{ project.name }}


- name: Create Nginx symlink
  file:
    path: /etc/nginx/sites-enabled/{{ project.name }}.conf
    src: "{{ host.home }}conf/nginx.conf"
    force: true
    state: link

  notify:
    - restart nginx