---

- name: Update package repository
  apt:
    update_cache: true
    cache_valid_time: 3600


- name: Install system packages
  apt:
    name: "{{ item }}"
    install_recommends: true
    state: present

  with_items:
    - nginx


- name: Create Nginx configuration file
  template:
    src: nginx.j2
    dest: /etc/nginx/sites-enabled/{{ project.name }}

  notify: restart nginx