---

- name: Update package repository
  apt:
    update_cache: true
    cache_valid_time: 3600


- name: Install system packages
  apt:
    name: "{{ item }}"
    install_recommends: true
    state: present

  with_items:
    - uwsgi
    - uwsgi-plugin-{{ python.version }}


- name: Create uWSGI configuration file
  template:
    src: uwsgi.ini.j2
    dest: "{{ host.home }}/conf/uwsgi.ini"

- name: Create uWSGI symlink
  file:
    path: /etc/uwsgi/apps-enabled/{{ project.name }}.ini
    src: "{{ host.home }}/conf/uwsgi.ini"
    force: true
    state: link

  notify: restart uwsgi
