---

- name: UWSGI | Install system packages
  package:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present

  with_items:
    - uwsgi
    - uwsgi-plugin-{{ python.version }}


- name: UWSGI | Create uWSGI configuration file
  template:
    src: uwsgi.ini.j2
    dest: "{{ host.home }}conf/uwsgi.ini"

  notify: restart uwsgi


- name: UWSGI | Create uWSGI symlink
  file:
    path: /etc/uwsgi/apps-enabled/{{ project.name }}.ini
    src: "{{ host.home }}conf/uwsgi.ini"
    force: true
    state: link

  notify: restart uwsgi
