---

#- name: Update package repository
#  apt:
#    update_cache: true
#    cache_valid_time: 3600
#
#
#- name: Install system packages
#  apt:
#    name: "{{ item }}"
#    install_recommends: true
#    state: present
#
#  with_items:
#    - uwsgi


- name: Create uWSGI configuration file
  template:
    src: uwsgi.ini.j2
    dest: /etc/uwsgi/apps-enabled/{{ project.name }}.ini

  notify: restart uwsgi
