---

- name: Deploy application
  hosts: "{{ env }}"
  user: root
  vars:
    deploy: true
  vars_files:
    - group_vars/external/{{ env }}.yml
    - group_vars/all.yml

  roles:
    #- letsencrypt
#    - { role: nginx, when: skip_database is not defined }
    - django
    - supervisor