---

- name: Setup DB and web servers
  hosts: "{{ env }}"
  user: root
  vars_files:
    - group_vars/external/{{ env }}.yml
    - group_vars/all.yml

  roles:
#    - package
#    - user
#    - postgres
    - { role: nginx, when: skip_database is not defined }
#    - { role: redis, when: skip_database is not defined }
#    - django
#    - gunicorn
#    - { role: letsencrypt, when: skip_database is not defined }
#    - supervisor
