---

- name: Setup web server
  hosts: "{{ env }}"
  user: root
  vars_files:
    - group_vars/external/{{ env }}.yml
    - group_vars/all.yml


  roles:
    - package
    - user
    - local-folders
    - postgres
    - redis
    - nginx
    - django
    - gunicorn
    - letsencrypt
    - supervisor
