---

- name: Setup web server
  hosts: all
  user: root
  vars_files:
    - group_vars/external/{{ project_name }}.yml


  roles:
#    - package
    - user
#    - postgres
    - django
#    - letsencrypt
    - nginx
    - uwsgi
    - supervisor
