---

- name: SYSTEM | Create "{{ host.user }}" user with {{ host.home }} home and add to sudo group.
  become: true
  user:
    name: "{{ host.user }}"
    home: "{{ host.home }}"
    password: "{{ password }}"
    update_password: always
    shell: /bin/bash
#    groups: sudo
    append: true
    generate_ssh_key: true
    state: present
