---

#- name: restart supervisor
#  become: true
#  supervisorctl:
#    name: uwsgi
#    config: /etc/supervisor/supervisord.conf
#    state: restarted

- name: restart supervisor
  become: true
  service:
    name: supervisor.service
    enabled: true
    state: restarted