---

- name: SUPERVISOR | Install system packages
  apt:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present

  with_items:
    - supervisor


- name: SUPERVISOR | Create Supervisor configuration file
  become: true
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/supervisord.conf

  notify:
    - restart supervisor