---

- name: Update package repository
  apt:
    update_cache: true
    cache_valid_time: 3600


- name: Install system packages
  apt:
    name: "{{ item }}"
    install_recommends: true
    state: present

  with_items:
    - supervisor


- name: Create Supervisor configuration file
  become: true
  template:
    src: supervisor.j2
    dest: /etc/supervisor/conf.d/supervisor.conf

  notify:
    - restart supervisor