---

- name: GIT | Clone "{{ project.repo.url }}" repository to {{ project.path }}
  become: true
  git:
    repo: "{{ project.repo.url }}"
    dest: "{{ project.path }}"
    accept_hostkey: true
    version: "{{ project.repo.branch }}"

  notify: restart uwsgi

- name: Create local directories
  file:
    path: "{{ project.path }}{{ item }}"
    state: directory

  with_items:
    - log
    - media
    - config

#- name: Set permissions
#  file:
#    dest: "{{ host.home }}"
#    owner: "{{ host.user }}"
#    group: "{{ host.user }}"
#    recurse: true

- name: Install requirements to "{{ project.env.path }}"
  become: true
  become_user: "{{ host.user }}"
  pip:
    virtualenv: "{{ project.env.path }}"
    virtualenv_python: "{{ python.version }}"
    requirements: "{{ project.reqs_path }}"

  notify: restart uwsgi

- name: Activate environment
  shell: . {{ project.env.path }}bin/activate


- name: Copy YAML config file
  template:
    src: config.yml
    dest: "{{ project.path }}config/config.yml"


- name: Set permissions
  file:
    dest: "{{ host.home }}"
    owner: "{{ host.user }}"
    group: "{{ host.user }}"
    recurse: true


- name: Migrate the database
  #become: true
  #become_user: "{{ host.user }}"
  command: "{{ project.env.python }} {{ project.path }}manage.py migrate"


- name: Collect static files
  #become: true
  #become_user: "{{ host.user }}"
  expect:
    command: "{{ project.env.python }} {{ project.path }}/manage.py collectstatic"
    responses:
      'yes': 'yes'