---


- name: Clone "{{ project.repo.url }}" repository to "{{ project.path }}"
  git:
    repo: "{{ project.repo.url }}"
    dest: "{{ project.path }}"
    accept_hostkey: true
    version: "{{ project.repo.branch }}"


- name: Change git config to ignore file mode change
  git_config:
    name: core.filemode
    scope: local
    repo: "{{ project.path }}"
    value: false


- name: Upgrade pip
  pip:
    extra_args: --upgrade
    name:
      - pip
      - setuptools


- name: Install requirements to "{{ project.env.path }}"
  pip:
    virtualenv: "{{ project.env.path }}"
    requirements: "{{ project.reqs_path }}"
    virtualenv_command: "{{ python.version }}"
    extra_args: "-m venv {{ project.name }}"
    #executable: pip


- name: Expand local settings
  template:
    src: local_settings.j2
    dest: "{{ django.settings_template }}"


- name: Create local directories
  file:
    path: "{{ project.path }}/{{ item }}"
    state: directory
    mode: 0755

  with_items:
    - log
    - media


- name: Set permissions
  file:
    dest: "/home/{{ host.user }}"
    owner: "{{ host.user }}"
    group: "{{ host.user }}"
    mode: 0775
    recurse: true


- name: Migrate the database
  become: true
  become_user: "{{ host.user }}"
  command: "{{ project.env.python }} {{ project.path }}/manage.py migrate"


#- name: Collect static files
#  become: true
#  become_user: "{{ host.user }}"
#  command: "{{ project.env_path}}/bin/{{ python.version}} {{ project.path }}/manage.py collectstatic"
