---
# copy this template as config.yml in the same folder and change your configuration values

#django_debug: true

# production only
#django_allowed_hosts:
#  - '139.162.138.55'

django_secret_key: 'random_str'

# comment this entire key to use sqlite3
django_database:
  backend: 'postgresql_psycopg2'
  name: '{{ database.name }}'
  user: '{{ database.owner }}'
  password: '{{ database.password }}'
  host: '{{ database.host }}'
  port: '5432'

django_redis:
  location: 'redis://localhost:6379/0'

django_log:
  path: '{{ project.path }}log'

django_email:
  backend: 'console' # 'console', 'smtp'
  host: 'smtp.example.com'
  host_user: 'user'
  host_password: 'pass'

django_admin:
  name: '{{ admin.name }}'
  email: '{{ admin.email }}'

django_static:
  root: '{{ host.home }}static'

django_cloudinary:
  cloud_name: ''
  api_key: ''
  api_secret: ''
