---
# copy this template as config.yml in the same folder and change your configuration values

#django_debug: true

# production only
#django_allowed_hosts:
#  - '139.162.138.55'

django_secret_key: '{{ secret_key }}'

# comment this entire key to use sqlite3
django_database:
  backend: 'postgresql_psycopg2'
  name: '{{ database.name }}'
  user: '{{ database.owner }}'
  password: '{{ database.password }}'
  host: '{{ database.host }}'
  port: '5432'

django_redis:
  location: 'redis://{{ redis_host }}:6379/0'

django_log:
  path: '{{ project.log }}'

django_email:
  backend: '{{ email_backend }}' # 'console', 'smtp'
  host: '{{ email_host }}'
  host_user: '{{ email_user }}'
  host_password: '{{ email_pass }}'

django_admin:
  name: '{{ admin.name }}'
  email: '{{ admin.email }}'

django_static:
  root: '{{ host.home }}static/'

django_media:
  root: '{{ host.home }}uploads/'

django_log:
  path: '{{ host.home }}log/'


django_cloudinary:
  cloud_name: '{{ cloudinary_cloud_name }}'
  api_key: '{{ cloudinary_api_key }}'
  api_secret: '{{ cloudinary_api_secret }}'
