---

- name: Update package repository
  apt:
    update_cache: true
    cache_valid_time: 3600


- name: Install system packages
  apt:
    name: "{{ item }}"
    install_recommends: true
    state: present

  with_items:
    - build-essential
    - "{{ python.version }}-pil"
    - "{{ python.version }}-setuptools"
    - "{{ python.version }}-dev"
    - "{{ python.version }}-venv"
    - "{{ python.version }}-pip"
    - "{{ python.version }}-psycopg2"
    - python-pycryptopp
    - git
    - git-flow
    - redis-server
    - uwsgi
    - gettext