---

- name: POSTGRESQL | Install PostgreSQL server
  become: true
  package:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present
  with_items:
    - postgresql-{{ pg_version }}
    - postgresql-server-dev-{{ pg_version }}
  when: skip_database is not defined


- name: POSTGRESQL | Install Psycopg2
  become: true
  package:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present

  with_items:
    - libpq-dev
    - python-psycopg2
    - python3-psycopg2


- name: POSTGRESQL | Update pg_hba.conf file
  become: true
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0640
  when: skip_database is not defined
  notify:
    - restart postgresql


- name: POSTGRESQL | Update postgresql.conf file
  become: true
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0640
  when: skip_database is not defined
  notify:
    - restart postgresql


- name: POSTGRESQL | Restart PostgreSQL
  become: true
  service:
    name: postgresql
    state: restarted
  when: skip_database is not defined


- name: POSTGRESQL | Create PostgreSQL user '{{ database.owner }}'
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ database.name }}"
    password: "{{ database.password }}"
    state: present
  when: skip_database is not defined


- name: POSTGRESQL | Create PostgreSQL database '{{ database.name }}' with owner '{{ database.owner }}'
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ database.name }}"
    owner: "{{ database.owner }}"
    encoding: UTF-8
    lc_collate: hr_HR.UTF-8
    lc_ctype: hr_HR.UTF-8
    template: template0
    state: present
  when: skip_database is not defined