---

- name: Install system packages
  package:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present

  with_items:
    - letsencrypt


- name: Stop nginx temporarily if it's running
  become: true
  service:
    name: nginx
    state: stopped


- name: SSL | Generate Diffie-Hellman params
  become: true
  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048


- name: Create Letsencrypt certificate
  become: true
  shell: letsencrypt certonly -n --standalone --agree-tos -m {{ letsencrypt.email }} -d {{ item }}
  args:
    creates: /etc/ssl/live/{{ item }}

  with_items: "{{ domains }}"

#  notify:
#    - restart nginx


- name: Create Letsencrypt cronjob for automatic certificate renewal
  #become: true
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: letsencrypt --renew certonly -n --standalone --agree-tos -m {{ letsencrypt.email }} -d {{ item }}

  with_items: "{{ domains }}"
