---

- name: Install system packages
  package:
    name: "{{ item }}"
    install_recommends: true
    update_cache: true
    cache_valid_time: 3600
    state: present

  with_items:
    - letsencrypt


#- name: Stop nginx temporarily if it's running
#  become: true
#  service:
#    name: nginx
#    state: stopped


#- name: SSL | Generate Diffie-Hellman params
#  become: true
#  command: openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048


- name: Create Letsencrypt certificate script
  become: true
  template:
    src: letsencrypt.sh.j2
    dest: "{{ host.home }}letsencrypt.sh"
    mode: 0777


- name: Create Letsencrypt renewal script
  become: true
  template:
    src: letsencrypt-renew.sh.j2
    dest: "{{ host.home }}letsencrypt-renew.sh"
    mode: 0777


- name: Execute Letsencrypt certificate script
  become: true
  shell: "{{ host.home }}letsencrypt-renew.sh"
#  notify:
#    - restart nginx


- name: Create Letsencrypt cronjob for automatic certificate renewal
  #become: true
  cron:
    name: letsencrypt_renewal
    special_time: weekly
    job: "{{ host.home}}letsencrypt-renew.sh"

